spring:
  datasource:
    url: jdbc:mysql://localhost:3306/icecream
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ice
    password: icecream

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true

    generate-ddl: true
    hibernate:
      ddl-auto: update

jwt:
  access-token-valid-time: ${JWT_ACCESS_TIME}
  prefix: Bearer
  header: Authorization
  secret-key: ${JWT_SECRET}

debug: true
---
spring:
  config:
    activate:
      on-profile: prod

  datasource:
    url: jdbc:mysql://imom-database:${DB_PORT}/${DB_NAME}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
